// Printed parts (sim/printing.cpp and their structural studies) against theory: slicer profiles read from each slicer's
// files, the road's fill, the skins' laminate (classical lamination theory), the failure criterion in a region's axes, the
// infill region's volume, and studies of printed bodies: a cantilever's tip deflection, top-skin stress and first
// frequency against composite beam theory with the infill along and across it, its printed mass, a bar pulled along its
// layers and across them, and the averaged-out grid infill against an explicit grid of walls. Studies are skipped when
// ccx is not installed.
#include <BRepGProp.hxx>
#include <BRepPrimAPI_MakeBox.hxx>
#include <BRepPrimAPI_MakeCylinder.hxx>
#include <GProp_GProps.hxx>

#include <chrono>
#include <cmath>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <string>
#include <vector>

#include "check.hpp"
#include "opad/core.hpp"
#include "opad/sim/fea.hpp"
#include "opad/sim/printing.hpp"

using namespace opad;
namespace fs = std::filesystem;

namespace {

constexpr double kPi = 3.14159265358979323846;

bool engines_ok() { return sim::engines().value("static", false); }

struct Dir {
  fs::path p;
  Dir() {
    p = fs::temp_directory_path() / ("opad-print-" + std::to_string(std::chrono::steady_clock::now().time_since_epoch().count()));
    fs::create_directories(p);
  }
  ~Dir() {
    std::error_code e;
    fs::remove_all(p, e);
  }
  fs::path write(const std::string& name, const std::string& text) const {
    std::ofstream(p / name, std::ios::binary) << text;
    return p / name;
  }
};

// A zip of stored (uncompressed) entries, as a 3MF holds them.
std::string stored_zip(const std::vector<std::pair<std::string, std::string>>& entries) {
  auto crc32 = [](const std::string& s) {
    uint32_t c = 0xFFFFFFFFu;
    for (unsigned char b : s) {
      c ^= b;
      for (int k = 0; k < 8; ++k) c = (c >> 1) ^ (0xEDB88320u & (0u - (c & 1u)));
    }
    return ~c;
  };
  std::string out, dir;
  auto u16 = [](std::string& s, uint32_t v) { s += char(v & 0xFF), s += char((v >> 8) & 0xFF); };
  auto u32 = [&](std::string& s, uint32_t v) { u16(s, v & 0xFFFF), u16(s, v >> 16); };
  for (const auto& [name, data] : entries) {
    const uint32_t crc = crc32(data), at = uint32_t(out.size()), n = uint32_t(data.size());
    u32(out, 0x04034b50), u16(out, 20), u16(out, 0), u16(out, 0), u16(out, 0), u16(out, 0), u32(out, crc), u32(out, n), u32(out, n);
    u16(out, uint32_t(name.size())), u16(out, 0);
    out += name + data;
    u32(dir, 0x02014b50), u16(dir, 20), u16(dir, 20), u16(dir, 0), u16(dir, 0), u16(dir, 0), u16(dir, 0), u32(dir, crc), u32(dir, n), u32(dir, n);
    u16(dir, uint32_t(name.size())), u16(dir, 0), u16(dir, 0), u16(dir, 0), u16(dir, 0), u32(dir, 0), u32(dir, at);
    dir += name;
  }
  const uint32_t at = uint32_t(out.size());
  out += dir;
  u32(out, 0x06054b50), u16(out, 0), u16(out, 0), u16(out, uint32_t(entries.size())), u16(out, uint32_t(entries.size()));
  u32(out, uint32_t(dir.size())), u32(out, at), u16(out, 0);
  return out;
}

double volume(const TopoDS_Shape& s) {
  GProp_GProps g;
  BRepGProp::VolumeProperties(s, g);
  return g.Mass();
}

std::string box(Document& doc, Vec3 at, double l, double w, double h, const std::string& name, const std::string& join = {}) {
  json inputs = {{"plane", {{"origin", at}, {"normal", {0, 0, 1}}}}, {"length", l}, {"width", w}, {"height", h}, {"centered", false}};
  if (!join.empty()) inputs["operation"] = "join", inputs["targets"] = {join};
  const json r = commands::run("feature", {{"kind", "box"}, {"name", name}, {"inputs", inputs}}, &doc);
  return join.empty() ? r["body_ids"][0].get<std::string>() : join;
}

json faces_at(const std::string& body, const char* axis, double value, bool one = true) {
  json j = {{"body", body}, {"kind", "face"}, {"select", {{"surface", "plane"}, {"at_plane", {{"axis", axis}, {"value", value}}}}}};
  if (one) j["expect"] = 1;
  return j;
}

// A layer's road fill: a stadium h high and w wide in its h x w box.
double stadium(double h, double w) { return 1 - (1 - kPi / 4) * h / w; }

// The stiffness of an orthotropic layer at theta degrees to its axis 1 (rotated about 3).
double rotated_E(const sim::Ortho& m, double theta) {
  const double c = std::cos(theta * kPi / 180), s = std::sin(theta * kPi / 180);
  return 1 / (c * c * c * c / m.E1 + s * s * s * s / m.E2 + (1 / m.G12 - 2 * m.nu12 / m.E1) * c * c * s * s);
}

}  // namespace

TEST(profiles_from_each_slicer) {
  Dir d;
  // PrusaSlicer: an exported config bundle's print and filament keys; widths as a share of the nozzle.
  json p = sim::read_profile(d.write("prusa.ini", "# generated by PrusaSlicer\nlayer_height = 0.15\nperimeters = 3\ntop_solid_layers = 5\n"
                                                  "bottom_solid_layers = 3\nfill_density = 15%\nfill_pattern = gyroid\nfill_angle = 30\n"
                                                  "perimeter_extrusion_width = 112.5%\nnozzle_diameter = 0.4\nextrusion_multiplier = 0.95\n"
                                                  "filament_type = PETG\n"));
  CHECK_EQ(p["walls"].get<int>(), 3);
  CHECK_EQ(p["top_layers"].get<int>(), 5);
  CHECK_EQ(p["bottom_layers"].get<int>(), 3);
  CHECK_NEAR(p["layer_height"].get<double>(), 0.15, 1e-12);
  CHECK_NEAR(p["line_width"].get<double>(), 0.45, 1e-12);
  CHECK_NEAR(p["infill"].get<double>(), 15, 1e-12);
  CHECK_EQ(p["pattern"].get<std::string>(), std::string("gyroid"));
  CHECK_NEAR(p["infill_angle"].get<double>(), 30, 1e-12);
  CHECK_NEAR(p["flow"].get<double>(), 0.95, 1e-12);
  CHECK_EQ(p["material"].get<std::string>(), std::string("PETG"));
  // OrcaSlicer / Bambu Studio: JSON, values as strings or one-element lists.
  p = sim::read_profile(d.write("orca.json", R"({"layer_height": "0.2", "wall_loops": "4", "top_shell_layers": "6", "bottom_shell_layers": "4",
      "sparse_infill_density": "25%", "sparse_infill_pattern": "grid", "inner_wall_line_width": "0.42", "filament_type": ["PLA-CF"],
      "filament_flow_ratio": ["0.98"]})"));
  CHECK_EQ(p["walls"].get<int>(), 4);
  CHECK_EQ(p["top_layers"].get<int>(), 6);
  CHECK_NEAR(p["line_width"].get<double>(), 0.42, 1e-12);
  CHECK_NEAR(p["infill"].get<double>(), 25, 1e-12);
  CHECK_NEAR(p["flow"].get<double>(), 0.98, 1e-12);
  const sim::PrintSettings orca = sim::print_settings({{"profile", path_to_utf8(d.p / "orca.json")}});
  CHECK_EQ(orca.material.id, std::string("pla-cf"));
  CHECK_EQ(orca.family, std::string("grid"));
  CHECK_NEAR(orca.wall_thickness(), 4 * 0.42, 1e-12);
  // Cura: a quality profile's [values], flow as a percentage.
  p = sim::read_profile(d.write("fine.inst.cfg", "[general]\nversion = 4\nname = Fine\n\n[metadata]\ntype = quality\n\n[values]\n"
                                                 "layer_height = 0.1\nwall_line_count = 2\ntop_layers = 8\nbottom_layers = 6\n"
                                                 "infill_sparse_density = 40\ninfill_pattern = triangles\nwall_line_width = 0.4\n"
                                                 "material_flow = 102\n"));
  CHECK_NEAR(p["layer_height"].get<double>(), 0.1, 1e-12);
  CHECK_EQ(p["top_layers"].get<int>(), 8);
  CHECK_NEAR(p["infill"].get<double>(), 40, 1e-12);
  CHECK_NEAR(p["flow"].get<double>(), 1.02, 1e-12);
  CHECK_EQ(sim::infill_family(p["pattern"].get<std::string>()), std::string("triangles"));
  // G-code: the settings the slicer appended at its end.
  p = sim::read_profile(d.write("part.gcode", "G1 X10 Y10 E1\nG1 X20 Y10 E2\n; prusaslicer_config = begin\n; layer_height = 0.3\n"
                                              "; perimeters = 2\n; fill_density = 50%\n; fill_pattern = honeycomb\n"
                                              "; perimeter_extrusion_width = 0.5\n; prusaslicer_config = end\n"));
  CHECK_NEAR(p["layer_height"].get<double>(), 0.3, 1e-12);
  CHECK_NEAR(p["infill"].get<double>(), 50, 1e-12);
  CHECK_EQ(p["pattern"].get<std::string>(), std::string("honeycomb"));
  // 3MF projects: PrusaSlicer's "; key = value" and Orca's JSON inside the zip.
  {
    std::ofstream(d.p / "prusa.3mf", std::ios::binary)
        << stored_zip({{"3D/3dmodel.model", "<model/>"}, {"Metadata/Slic3r_PE.config", "; perimeters = 5\n; fill_density = 35%\n; fill_pattern = cubic\n"}});
    p = sim::read_profile(d.p / "prusa.3mf");
    CHECK_EQ(p["walls"].get<int>(), 5);
    CHECK_EQ(p["pattern"].get<std::string>(), std::string("cubic"));
    std::ofstream(d.p / "orca.3mf", std::ios::binary)
        << stored_zip({{"3D/3dmodel.model", "<model/>"}, {"Metadata/project_settings.config", R"({"wall_loops": "3", "sparse_infill_density": "10%"})"}});
    p = sim::read_profile(d.p / "orca.3mf");
    CHECK_EQ(p["walls"].get<int>(), 3);
    CHECK_NEAR(p["infill"].get<double>(), 10, 1e-12);
    std::ofstream(d.p / "bare.3mf", std::ios::binary) << stored_zip({{"3D/3dmodel.model", "<model/>"}});
    CHECK_THROWS(sim::read_profile(d.p / "bare.3mf"));
  }
  CHECK_THROWS(sim::read_profile(d.write("empty.ini", "# nothing a slicer wrote\n")));
  CHECK_THROWS(sim::read_profile(d.p / "missing.ini"));
}

TEST(settings_and_their_checks) {
  // Keys given override the profile's; the filament's values can be adjusted from your own test bars.
  Dir d;
  const auto ini = d.write("p.ini", "perimeters = 3\nfill_density = 20%\nfill_pattern = rectilinear\nlayer_height = 0.2\n");
  sim::PrintSettings s = sim::print_settings({{"profile", path_to_utf8(ini)}, {"walls", 5}, {"material", {{"base", "petg"}, {"Z", 12}}}});
  CHECK_EQ(s.walls, 5);
  CHECK_EQ(s.family, std::string("lines"));
  CHECK_NEAR(s.density, 0.2, 1e-12);
  CHECK_NEAR(s.material.Z, 12, 1e-12);
  CHECK_NEAR(s.material.E, sim::filament("petg")->E, 1e-12);
  CHECK(s.source == path_to_utf8(ini));
  // 100 % prints solid whatever the pattern.
  CHECK_EQ(sim::print_settings({{"infill", 100}, {"pattern", "gyroid"}}).family, std::string("solid"));
  CHECK(sim::filament("PA-CF") && sim::filament("PA-CF")->id == "pa-cf");
  CHECK_THROWS(sim::print_settings({{"pattern", "voronoi"}}));
  CHECK_THROWS(sim::print_settings({{"material", "unobtainium"}}));
  CHECK_THROWS(sim::print_settings({{"layer_height", 0}}));
  CHECK_THROWS(sim::print_settings({{"walls", -1}}));
  CHECK_THROWS(sim::print_settings({{"infill", "lots"}}));
  CHECK_THROWS(sim::print_settings(json::array()));
}

TEST(road_fill_and_wall_material) {
  // A 0.2 x 0.45 road fills 1 - (1 - pi/4) 0.2 / 0.45 of its box; flow scales it, never past full.
  sim::PrintSettings s = sim::print_settings({{"material", "pla"}});
  CHECK_NEAR(s.fill(), stadium(0.2, 0.45), 1e-12);
  CHECK_NEAR(sim::print_settings({{"flow", 0.9}}).fill(), 0.9 * stadium(0.2, 0.45), 1e-12);
  CHECK_NEAR(sim::print_settings({{"flow", 1.2}}).fill(), 1.0, 1e-12);
  // Walls: the filament's along-road, across-road and between-layer values, times the fill.
  const sim::Filament& f = s.material;
  const sim::Ortho w = sim::region_material(s, sim::Region::Wall);
  const double phi = s.fill();
  CHECK_NEAR(w.E1, phi * f.E, 1e-9);
  CHECK_NEAR(w.E2, phi * f.kt * f.E, 1e-9);
  CHECK_NEAR(w.E3, phi * f.kz * f.E, 1e-9);
  CHECK_NEAR(w.X, phi * f.X, 1e-9);
  CHECK_NEAR(w.Z, phi * f.Z, 1e-9);
  CHECK_NEAR(w.Zc, phi * f.C, 1e-9);
  CHECK_NEAR(w.density, phi * f.density, 1e-12);
}

TEST(skins_are_a_cross_ply_laminate) {
  // Top and bottom layers at 0 and 90 deg: classical lamination theory gives E = (A11^2 - A12^2) / A11 both ways, with
  // A11 = (Q11 + Q22) / 2 and A12 = Q12 of one ply.
  sim::PrintSettings s = sim::print_settings({{"infill_angle", 0}});
  const sim::Filament& f = s.material;
  const double phi = s.fill(), E1 = phi * f.E, E2 = phi * f.kt * f.E, nu12 = f.nu, nu21 = nu12 * E2 / E1;
  const double Q11 = E1 / (1 - nu12 * nu21), Q22 = E2 / (1 - nu12 * nu21), Q12 = nu12 * E2 / (1 - nu12 * nu21);
  const double A11 = (Q11 + Q22) / 2, A12 = Q12;
  const sim::Ortho t = sim::region_material(s, sim::Region::TopBottom);
  CHECK_NEAR(t.E1, (A11 * A11 - A12 * A12) / A11, 1e-6 * t.E1);
  CHECK_NEAR(t.E2, t.E1, 1e-6 * t.E1);
  CHECK_NEAR(t.E3, phi * f.kz * f.E, 1e-9);
  // Pulled along a ply, that ply fails first, at less than the road's strength X (it carries more than its share).
  CHECK(t.X > 0.5 * phi * f.X && t.X < phi * f.X);
  // At +-45 deg: Qbar11 = (Q11 + Q22 + 2 Q12 + 4 Q66) / 4 and Qbar12 = (Q11 + Q22 - 4 Q66) / 4 + Q12 / 2 in both plies.
  const double Q66 = phi * f.kt * f.E / (2 * (1 + f.nu));
  const double B11 = (Q11 + Q22 + 2 * Q12 + 4 * Q66) / 4, B12 = (Q11 + Q22 - 4 * Q66) / 4 + Q12 / 2;
  const sim::Ortho t45 = sim::region_material(sim::print_settings({{"infill_angle", 45}}), sim::Region::TopBottom);
  CHECK_NEAR(t45.E1, (B11 * B11 - B12 * B12) / B11, 1e-6 * t45.E1);
  // 100 % infill is the same laminate (at the infill's own axes).
  const sim::Ortho solid = sim::region_material(sim::print_settings({{"infill", 100}, {"infill_angle", 0}}), sim::Region::Core);
  CHECK_NEAR(solid.E1, t.E1, 1e-6 * t.E1);
}

TEST(infill_models) {
  // A square grid: rho = 2 t/a - (t/a)^2 of plastic, t/a of it along each axis; walls standing the full height.
  const sim::PrintSettings s = sim::print_settings({{"infill", 20}, {"pattern", "grid"}});
  const double rho = 0.2 * s.fill(), ta = 1 - std::sqrt(1 - rho);
  CHECK_NEAR(2 * ta - ta * ta, rho, 1e-12);
  const sim::Ortho g = sim::region_material(s, sim::Region::Core);
  CHECK_NEAR(g.E1, ta * s.material.E, 1e-9);
  CHECK_NEAR(g.E3, rho * s.material.kz * s.material.E, 1e-9);
  CHECK_NEAR(g.G12, ta * ta * ta * s.material.E / 2, 1e-9);  // walls bending between crossings
  CHECK_NEAR(g.density, rho * s.material.density, 1e-12);
  // Stretching patterns are stiffer in plane than bending ones at the same density; every pattern gets stiffer with it.
  auto E1 = [](const char* pattern, double infill) { return sim::region_material(sim::print_settings({{"infill", infill}, {"pattern", pattern}}), sim::Region::Core).E1; };
  CHECK(E1("triangles", 20) > E1("honeycomb", 20));
  CHECK(E1("grid", 20) > E1("gyroid", 20));
  for (const char* p : {"lines", "grid", "triangles", "honeycomb", "cubic", "gyroid", "lightning", "concentric"}) {
    CHECK(E1(p, 40) > E1(p, 10));
    const sim::Ortho o = sim::region_material(sim::print_settings({{"infill", 15}, {"pattern", p}}), sim::Region::Core);
    // An admissible orthotropic material: 1 - nu12 nu21 - ... > 0.
    const double n21 = o.nu12 * o.E2 / o.E1, n31 = o.nu13 * o.E3 / o.E1, n32 = o.nu23 * o.E3 / o.E2;
    CHECK(1 - o.nu12 * n21 - o.nu23 * n32 - o.nu13 * n31 - 2 * n21 * n32 * o.nu13 > 0);
  }
}

TEST(failure_criterion_in_region_axes) {
  const sim::Ortho m = sim::region_material(sim::print_settings(json::object()), sim::Region::Wall);
  const Vec3 x{1, 0, 0}, y{0, 1, 0}, z{0, 0, 1};
  // Uniaxial at each strength: index 1, and the mode that names it.
  sim::Failure f = sim::failure({m.X, 0, 0, 0, 0, 0}, x, y, z, m);
  CHECK_NEAR(f.index, 1, 1e-12);
  CHECK_EQ(f.mode, std::string("along the roads"));
  f = sim::failure({0, m.Y, 0, 0, 0, 0}, x, y, z, m);
  CHECK_NEAR(f.index, 1, 1e-12);
  CHECK_EQ(f.mode, std::string("across the roads"));
  f = sim::failure({0, 0, m.Z, 0, 0, 0}, x, y, z, m);
  CHECK_NEAR(f.index, 1, 1e-12);
  CHECK_EQ(f.mode, std::string("between layers"));
  f = sim::failure({0, 0, 0, 0, 0.5 * m.S23, 0}, x, y, z, m);
  CHECK_NEAR(f.index, 0.25, 1e-12);
  CHECK_EQ(f.mode, std::string("shear"));
  // Pressed together the layers hold: compression across them against the plastic's compressive strength.
  CHECK(m.Zc > m.Z);
  f = sim::failure({0, 0, -m.Z, 0, 0, 0}, x, y, z, m);
  CHECK_NEAR(f.index, std::pow(m.Z / m.Zc, 2), 1e-12);
  f = sim::failure({0, 0, -m.Zc, 0, 0, 0}, x, y, z, m);
  CHECK_NEAR(f.index, 1, 1e-12);
  CHECK_EQ(f.mode, std::string("in compression"));
  // Half the strength: a quarter of the index (safety factor 2).
  CHECK_NEAR(sim::failure({0, 0, 0.5 * m.Z, 0, 0, 0}, x, y, z, m).index, 0.25, 1e-12);
  // Roads at 30 deg in the plane: a pull along them in world axes is a pull along the roads.
  const double c = std::cos(kPi / 6), s = std::sin(kPi / 6);
  const Vec3 a1{c, s, 0}, a2{-s, c, 0};
  f = sim::failure({m.X * c * c, m.X * s * s, 0, m.X * c * s, 0, 0}, a1, a2, z, m);
  CHECK_NEAR(f.index, 1, 1e-9);
  CHECK_EQ(f.mode, std::string("along the roads"));
  // An infill the same every way in its layer (gyroid) fails under the same in-plane pull along its axes or at 45 deg to
  // them, however weak it is between layers (that bond stays out of the layer's own criterion).
  const sim::Ortho g = sim::region_material(sim::print_settings({{"pattern", "gyroid"}, {"infill", 30}}), sim::Region::Core);
  const double r2 = std::sqrt(0.5), p = 0.8 * g.X;
  const double along = sim::failure({p, 0, 0, 0, 0, 0}, x, y, z, g).index, diagonal = sim::failure({p, 0, 0, 0, 0, 0}, {r2, r2, 0}, {-r2, r2, 0}, z, g).index;
  CHECK_NEAR(diagonal, along, 1e-9);
  CHECK_NEAR(along, 0.64, 1e-9);
  // Built on its side (layers stacked along world x): a pull along x is a pull between layers.
  f = sim::failure({m.Z, 0, 0, 0, 0, 0}, y, z, x, m);
  CHECK_NEAR(f.index, 1, 1e-12);
  CHECK_EQ(f.mode, std::string("between layers"));
}

TEST(infill_region_volume) {
  // What a slicer fills: walls in from the sides, top and bottom skins in from the faces looking up and down.
  const sim::PrintSettings s = sim::print_settings({{"walls", 2}, {"line_width", 0.45}, {"top_layers", 4}, {"bottom_layers", 3}, {"layer_height", 0.2}});
  const double tw = 0.9, tt = 0.8, tb = 0.6;
  const TopoDS_Shape core = sim::print_core(BRepPrimAPI_MakeBox(40, 20, 10).Shape(), s);
  CHECK(!core.IsNull());
  CHECK_NEAR(volume(core), (40 - 2 * tw) * (20 - 2 * tw) * (10 - tt - tb), 1e-3);
  const TopoDS_Shape ring = sim::print_core(BRepPrimAPI_MakeCylinder(15, 10).Shape(), s);
  CHECK_NEAR(volume(ring), kPi * (15 - tw) * (15 - tw) * (10 - tt - tb), 1e-3);
  // Built on its side: the skins are across x now.
  sim::PrintSettings side = s;
  side.up = {1, 0, 0};
  CHECK_NEAR(volume(sim::print_core(BRepPrimAPI_MakeBox(40, 20, 10).Shape(), side)), (40 - tt - tb) * (20 - 2 * tw) * (10 - 2 * tw), 1e-3);
  // Thinner than its skins: no infill.
  CHECK(sim::print_core(BRepPrimAPI_MakeBox(40, 20, 1.2).Shape(), s).IsNull());
}

namespace {
// A printed cantilever L x b x h along x, built flat (layers in x-y), held at x = 0 and loaded down at its end, and the
// composite beam theory for it: each region's stiffness along x times its share of the second moment of area.
struct PrintedBeam {
  double L = 200, b = 10, h = 10, P = 5;
  sim::PrintSettings s;
  double tw, tt, hc, EI_y, EI_z, GA, mass_g;
  explicit PrintedBeam(const json& print) : s(sim::print_settings(print)) {
    tw = s.wall_thickness(), tt = s.top_thickness(), hc = h - 2 * tt;
    const sim::Ortho w = sim::region_material(s, sim::Region::Wall), t = sim::region_material(s, sim::Region::TopBottom),
                     c = sim::region_material(s, sim::Region::Core);
    const double Ec = rotated_E(c, s.angle), bc = b - 2 * tw;
    const auto cube = [](double v) { return v * v * v; };
    EI_y = t.E1 * b * (cube(h) - cube(hc)) / 12 + w.E1 * 2 * tw * cube(hc) / 12 + Ec * bc * cube(hc) / 12;
    EI_z = t.E1 * 2 * tt * cube(b) / 12 + w.E1 * hc * (cube(b) - cube(bc)) / 12 + Ec * hc * cube(bc) / 12;
    GA = 5.0 / 6 * (t.G13 * b * 2 * tt + w.G13 * 2 * tw * hc + c.G13 * bc * hc);
    const double vc = (L - 2 * tw) * bc * hc;
    mass_g = (vc * c.density + (L * b * h - vc) * w.density) / 1000;
  }
};

sim::StudyRun run_beam(const PrintedBeam& pb, const std::string& kind, std::string* body = nullptr) {
  Document doc = Document::create();
  const std::string beam = box(doc, {0, 0, 0}, pb.L, pb.b, pb.h, "Beam");
  commands::run("load", {{"kind", "fixed"}, {"on", {faces_at(beam, "x", 0)}}}, &doc);
  if (kind == "static") commands::run("load", {{"kind", "force"}, {"on", {faces_at(beam, "x", pb.L)}}, {"vector", {0, 0, -pb.P}}}, &doc);
  if (body) *body = beam;
  const json print = {{"material", pb.s.material.id}, {"infill", pb.s.density * 100}, {"pattern", pb.s.pattern}, {"infill_angle", pb.s.angle}};
  return sim::run_study(doc, resolve(doc), {{"kind", kind}, {"settings", {{"mesh_size", 2}, {"modes", 2}, {"print", print}}}});
}
}  // namespace

TEST(printed_cantilever_against_composite_beam_theory) {
  if (!engines_ok()) return;
  // Grid infill along the beam, then at 45 deg: the core's stiffness along x drops to what its shear allows.
  for (const double angle : {0.0, 45.0}) {
    const PrintedBeam pb({{"material", "pla"}, {"infill", 20}, {"pattern", "grid"}, {"infill_angle", angle}});
    std::string beam;
    const sim::StudyRun run = run_beam(pb, "static", &beam);
    const double expected = pb.P * pb.L * pb.L * pb.L / (3 * pb.EI_y) + pb.P * pb.L / pb.GA;
    CHECK_NEAR(-sim::probe(*run.fea, {pb.L, pb.b / 2, pb.h / 2}, "dz"), expected, 0.03 * expected);
    // The top skin half way along: M z E_skin / EI (tension on top).
    const double t_E1 = sim::region_material(pb.s, sim::Region::TopBottom).E1;
    const double sigma = pb.P * (pb.L / 2) * (pb.h / 2) * t_E1 / pb.EI_y;
    CHECK_NEAR(sim::probe(*run.fea, {pb.L / 2, pb.b / 2, pb.h}, "sxx"), sigma, 0.04 * sigma);
    // What it is made of: the regions' volumes, and the plastic it takes.
    const json& pj = run.summary["print"]["Beam"];
    const json& reg = pj["regions"];
    CHECK_NEAR(reg["infill"]["volume_mm3"].get<double>(), (pb.L - 2 * pb.tw) * (pb.b - 2 * pb.tw) * pb.hc, 1e-3 * pb.L * pb.b * pb.h);
    CHECK_NEAR(reg["top/bottom"]["volume_mm3"].get<double>(), pb.L * pb.b * 2 * pb.tt, 1e-3 * pb.L * pb.b * pb.h);
    CHECK_NEAR(pj["printed_mass_g"].get<double>(), pb.mass_g, 0.005 * pb.mass_g);
    // Weakest in the top skin at the root, along its roads: its strength over the root's bending stress, less what the
    // clamp's corner adds.
    const sim::Ortho skin = sim::region_material(pb.s, sim::Region::TopBottom);
    const double nominal = skin.X / (pb.P * pb.L * (pb.h / 2) * skin.E1 / pb.EI_y);
    CHECK(pj["min_safety_factor"].get<double>() < 1.02 * nominal && pj["min_safety_factor"].get<double>() > 0.6 * nominal);
    CHECK_EQ(pj["fails"].get<std::string>(), std::string("along the roads (top/bottom)"));
    CHECK(pj["weakest_at"][0].get<double>() < 0.1 * pb.L);
  }
}

TEST(printed_cantilever_first_frequency) {
  if (!engines_ok()) return;
  // 1.8751^2 / 2 pi sqrt(EI / (m/L) L^4), the softer way first (EI_y and EI_z differ: the skins are on top and bottom).
  const PrintedBeam pb({{"material", "pla"}, {"infill", 20}, {"pattern", "grid"}, {"infill_angle", 0}});
  const sim::StudyRun run = run_beam(pb, "modal");
  const double mu = pb.mass_g * 1e-6 / pb.L;  // t/mm
  const double f1 = 1.8751 * 1.8751 / (2 * kPi) * std::sqrt(std::min(pb.EI_y, pb.EI_z) / (mu * std::pow(pb.L, 4)));
  CHECK(!run.fea->frequencies.empty());
  CHECK_NEAR(run.fea->frequencies.front(), f1, 0.03 * f1);
}

namespace {
// A 40 x 10 x 10 bar pulled at 10 MPa along x, all walls (no infill, no skins), built flat or standing on its end.
sim::StudyRun pulled_bar(const Vec3& up, std::string& bar) {
  Document doc = Document::create();
  bar = box(doc, {0, 0, 0}, 40, 10, 10, "Bar");
  commands::run("load", {{"kind", "fixed"}, {"on", {faces_at(bar, "x", 0)}}}, &doc);
  commands::run("load", {{"kind", "pressure"}, {"on", {faces_at(bar, "x", 40)}}, {"value", -10}}, &doc);
  const json print = {{"material", "pla"}, {"walls", 12}, {"top_layers", 0}, {"bottom_layers", 0}, {"build_direction", up}};
  return sim::run_study(doc, resolve(doc), {{"kind", "static"}, {"settings", {{"mesh_size", 2}, {"print", print}}}});
}
}  // namespace

TEST(bar_pulled_along_and_across_its_layers) {
  if (!engines_ok()) return;
  const sim::PrintSettings s = sim::print_settings({{"material", "pla"}});
  const double sigma = 10, phi = s.fill();
  // Flat: the pull runs along the roads; its index (sigma / X)^2.
  std::string bar;
  sim::StudyRun flat = pulled_bar({0, 0, 1}, bar);
  const double along = std::pow(sigma / (phi * s.material.X), 2);
  CHECK_NEAR(sim::probe(*flat.fea, {20, 5, 5}, "failure_index"), along, 0.05 * along);
  CHECK_NEAR(sim::probe(*flat.fea, {20, 5, 5}, "sxx"), sigma, 0.02 * sigma);
  const double e_along = sim::probe(*flat.fea, {30, 5, 5}, "dx") - sim::probe(*flat.fea, {10, 5, 5}, "dx");
  CHECK_NEAR(e_along, sigma * 20 / (phi * s.material.E), 0.02 * sigma * 20 / (phi * s.material.E));
  // (It is weakest where it is held: the end wall's roads run across the pull there.)
  CHECK(flat.summary["print"]["Bar"]["fails"].get<std::string>().find("between layers") == std::string::npos);
  // Standing on its end: the same pull opens the layers; (sigma / Z)^2, and it stretches by the between-layer stiffness.
  sim::StudyRun upright = pulled_bar({1, 0, 0}, bar);
  const double across = std::pow(sigma / (phi * s.material.Z), 2);
  CHECK_NEAR(sim::probe(*upright.fea, {20, 5, 5}, "failure_index"), across, 0.05 * across);  // an index: 2.5 % in stress (the worst element at the node)
  const double e_across = sim::probe(*upright.fea, {30, 5, 5}, "dx") - sim::probe(*upright.fea, {10, 5, 5}, "dx");
  const double kz = s.material.kz;
  CHECK_NEAR(e_across, sigma * 20 / (phi * kz * s.material.E), 0.02 * sigma * 20 / (phi * kz * s.material.E));
  CHECK(upright.summary["print"]["Bar"]["fails"].get<std::string>().find("between layers") == 0);
  CHECK(upright.summary["print"]["Bar"]["min_safety_factor"].get<double>() < flat.summary["print"]["Bar"]["min_safety_factor"].get<double>());
}

TEST(grid_infill_against_explicit_grid_walls) {
  if (!engines_ok()) return;
  // A 48 x 24 x 3 coupon of square cells a = 8 with walls t = 1.2 (rho = 2 t/a - (t/a)^2), stretched 0.1 mm along x: the
  // walls modelled one by one in solid plastic, against the block with the averaged-out grid infill in the same plastic
  // (isotropic roads that fill their box: kt = kz = 1, flow making up the stadium).
  const double L = 48, W = 24, H = 3, a = 8, t = 1.2, E = 3000, nu = 0.35, stretch = 0.1;
  const double rho = 2 * t / a - (t / a) * (t / a);
  auto reaction = [&](bool explicit_walls) {
    Document doc = Document::create();
    std::string body;
    if (explicit_walls) {
      for (double y = a / 2; y < W; y += a) body = box(doc, {0, y - t / 2, 0}, L, t, H, "Grid", body);
      for (double x = a / 2; x < L; x += a) body = box(doc, {x - t / 2, 0, 0}, t, W, H, "Grid", body);
    } else {
      body = box(doc, {0, 0, 0}, L, W, H, "Block");
    }
    commands::run("load", {{"kind", "fixed"}, {"on", {faces_at(body, "x", 0, !explicit_walls)}}}, &doc);
    commands::run("load", {{"kind", "displacement"}, {"on", {faces_at(body, "x", L, !explicit_walls)}}, {"vector", {stretch, 0, 0}}}, &doc);
    json settings = {{"mesh_size", explicit_walls ? 0.8 : 2.0}};
    if (explicit_walls) {
      settings["materials"] = {{"all", {{"E", E}, {"nu", nu}, {"density", 1.24}}}};
    } else {
      settings["print"] = {{"material", {{"base", "pla"}, {"E", E}, {"nu", nu}, {"kt", 1}, {"kz", 1}}}, {"walls", 0}, {"top_layers", 0},
                           {"bottom_layers", 0}, {"infill", rho * 100}, {"pattern", "grid"}, {"infill_angle", 0}, {"flow", 1 / stadium(0.2, 0.45)}};
    }
    const sim::StudyRun run = sim::run_study(doc, resolve(doc), {{"kind", "static"}, {"settings", settings}});
    return std::fabs(run.summary["reactions_N"]["Fixed 1"][0].get<double>());
  };
  const double walls = reaction(true), averaged = reaction(false);
  const double bars = E * (W / a) * t * H * stretch / L;  // the walls along x alone
  CHECK_NEAR(averaged, bars, 0.01 * bars);
  CHECK_NEAR(averaged, walls, 0.05 * walls);
}

CHECK_MAIN()
