# The job runner (app/Jobs.cpp) and its strip offscreen: busy cursor, "+N", the done signal (UI-109). Needs the app's Qt.
if(TARGET opad)
  target_sources(${target} PRIVATE ../app/Jobs.cpp ../app/Jobs.hpp ../app/ProgressStrip.cpp ../app/ProgressStrip.hpp ../app/Theme.cpp ../app/Theme.hpp ../app/Icons.cpp)
  set_target_properties(${target} PROPERTIES AUTOMOC ON)
  target_include_directories(${target} PRIVATE ../app)
  target_link_libraries(${target} PRIVATE Qt6::Widgets Qt6::Test)
  if(OPAD_STATIC)
    qt_import_plugins(${target} INCLUDE Qt6::QOffscreenIntegrationPlugin EXCLUDE_BY_TYPE imageformats iconengines)
  endif()
  set_tests_properties(${name} PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen" TIMEOUT 60)
else()
  set_target_properties(${target} PROPERTIES EXCLUDE_FROM_ALL ON)
  set_tests_properties(${name} PROPERTIES DISABLED ON)
endif()
