# Open file location and Copy path (app/FileLocation.cpp) built offscreen with its app sources; without the desktop app
# (no Qt) the test is not built.
if(TARGET opad)
  target_sources(${target} PRIVATE ../app/FileLocation.cpp ../app/Icons.cpp ../app/Theme.cpp ../app/Theme.hpp)
  set_target_properties(${target} PROPERTIES AUTOMOC ON)
  target_include_directories(${target} PRIVATE ../app)
  target_link_libraries(${target} PRIVATE Qt6::Widgets)
  if(OPAD_STATIC)
    qt_import_plugins(${target} INCLUDE Qt6::QOffscreenIntegrationPlugin EXCLUDE_BY_TYPE imageformats iconengines)
  endif()
  set_tests_properties(${name} PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen" TIMEOUT 60)
else()
  set_target_properties(${target} PROPERTIES EXCLUDE_FROM_ALL ON)
  set_tests_properties(${name} PROPERTIES DISABLED ON)
endif()
