# Third-party notices (TODO 11 UI-13): the packages a build ships, their versions, licences and where their source is,
# then the licence texts. Script mode, used two ways:
#   - included by cmake/portable_stage.cmake over the staged DLLs: THIRD-PARTY-NOTICES.txt beside opad.exe, the licence
#     files of each package in licenses/<package>/;
#   - run by a build step of core (core/CMakeLists.txt) over the link lines of opad.exe and opad-cli.exe in build.ninja:
#     the same list with the texts inline, compiled into the programs (opad::third_party_notices) for Help > Third-party
#     licences and `opad-cli licenses`, and copied beside the single-file exe.
# Packages come from MSYS2's pacman (-Qo per file, -Qi for version, licence and home page, -Ql for the files under
# share/licenses); without pacman the files are listed without packages.
#
# In: NOTICES_OUT (the text), NOTICES_FILES (binaries or headers, '|'-separated), NOTICES_NINJA + NOTICES_TARGETS
# (build.ninja and a regex of the outputs whose LINK_LIBRARIES to read), NOTICES_LIBDIRS (-l search path), NOTICES_LIBS
# (more -l names), NOTICES_STATIC, NOTICES_OWN (OPAD's build folder: its files are skipped), NOTICES_OCCT ("<install dir>|<version>|
# <source url>|<source dir>" of an OCCT built here), NOTICES_PACMAN, NOTICES_LICENSES_DIR (copy the licence files there
# instead of inlining them), NOTICES_SCOPE (what the list covers), NOTICES_VERSION, NOTICES_EXTRA (a file appended),
# NOTICES_CPP (also that C++ source, written only when it changed).

function(_opad_notices)
  string(REPLACE "|" ";" files "${NOTICES_FILES}")
  string(REPLACE "|" ";" libdirs "${NOTICES_LIBDIRS}")
  # -lname: the first library of that name on the search path, an archive first in a static build (as the linker does).
  set(kinds "lib<>.dll.a" "lib<>.a" "<>.lib")
  if(NOTICES_STATIC)
    set(kinds "lib<>.a" "lib<>.dll.a" "<>.lib")
  endif()
  macro(_opad_notice_lib name search)
    set(found "")
    foreach(dir IN LISTS ${search})
      foreach(kind IN LISTS kinds)
        string(REPLACE "<>" "${name}" candidate "${kind}")
        if(NOT found AND EXISTS "${dir}/${candidate}")
          set(found "${dir}/${candidate}")
        endif()
      endforeach()
    endforeach()
    if(found)
      list(APPEND files "${found}")
    endif()
  endmacro()
  string(REPLACE "|" ";" libs "${NOTICES_LIBS}")  # the compiler's implicit ones (C++ runtime, threads, CRT)
  foreach(name IN LISTS libs)
    _opad_notice_lib("${name}" libdirs)
  endforeach()
  # Link lines: every absolute library or object, every -lname resolved over -L and NOTICES_LIBDIRS.
  if(NOTICES_NINJA AND EXISTS "${NOTICES_NINJA}")
    get_filename_component(root "${NOTICES_NINJA}" DIRECTORY)
    file(STRINGS "${NOTICES_NINJA}" lines REGEX "^build [^:]+:|^  LINK_LIBRARIES = ")
    set(current "")
    foreach(line IN LISTS lines)
      if(line MATCHES "^build ([^:]+):")
        set(current "${CMAKE_MATCH_1}")
        continue()
      endif()
      if(NOT NOTICES_TARGETS OR NOT current MATCHES "${NOTICES_TARGETS}")
        continue()
      endif()
      string(REPLACE "  LINK_LIBRARIES = " "" line "${line}")
      string(REPLACE " " ";" tokens "${line}")
      set(search ${libdirs})
      foreach(token IN LISTS tokens)
        if(token MATCHES "^-L(.+)")
          list(APPEND search "${CMAKE_MATCH_1}")
        elseif(token MATCHES "^-l(.+)")
          _opad_notice_lib("${CMAKE_MATCH_1}" search)
        elseif(token MATCHES "^[A-Za-z]:/|^/")
          list(APPEND files "${token}")
        elseif(token MATCHES "\\.(a|lib|obj|o)$" AND NOT token MATCHES "^-")
          list(APPEND files "${root}/${token}")
        endif()
      endforeach()
    endforeach()
  endif()
  list(REMOVE_DUPLICATES files)

  # Sort: OPAD's own build output (skipped), an OCCT built here, the rest for pacman.
  string(REPLACE "|" ";" occt "${NOTICES_OCCT}")
  set(occt_install "")
  if(occt)
    list(GET occt 0 occt_install)
  endif()
  set(lookup "")
  set(occt_files "")
  foreach(f IN LISTS files)
    string(FIND "${f}" "${occt_install}/" in_occt)
    string(FIND "${f}" "${NOTICES_OWN}/" in_own)
    if(occt_install AND in_occt EQUAL 0)
      get_filename_component(n "${f}" NAME)
      list(APPEND occt_files "${n}")
    elseif(NOTICES_OWN AND in_own EQUAL 0)
    elseif(EXISTS "${f}")
      list(APPEND lookup "${f}")
    endif()
  endforeach()
  list(REMOVE_DUPLICATES occt_files)

  set(packages "")
  set(loose "")
  if(NOTICES_PACMAN AND lookup)
    get_filename_component(msys "${NOTICES_PACMAN}" DIRECTORY)  # <root>/usr/bin
    get_filename_component(msys "${msys}/../.." ABSOLUTE)
    execute_process(COMMAND "${NOTICES_PACMAN}" -Qo ${lookup} OUTPUT_VARIABLE out ERROR_VARIABLE err)
    string(REPLACE "\n" ";" out "${out}")
    foreach(line IN LISTS out)
      if(line MATCHES "^(.*) is owned by ([^ ]+) ([^ ]+)$")
        set(pkg "${CMAKE_MATCH_2}")
        get_filename_component(n "${CMAKE_MATCH_1}" NAME)
        list(APPEND packages "${pkg}")
        list(APPEND "files_${pkg}" "${n}")
      endif()
    endforeach()
    string(REGEX MATCHALL "No package owns [^\n]+" unowned "${err}")
    foreach(line IN LISTS unowned)
      string(REPLACE "No package owns " "" f "${line}")
      get_filename_component(n "${f}" NAME)
      list(APPEND loose "${n}")
    endforeach()
    list(REMOVE_DUPLICATES packages)
    list(SORT packages)
    # The GCC runtime linked into programs (libstdc++, libgcc) is the compiler package's; its licence files
    # (GPL-3.0 with the GCC Runtime Library Exception) are gcc-libs'.
    set(query ${packages})
    if("mingw-w64-x86_64-gcc" IN_LIST packages)
      list(APPEND query "mingw-w64-x86_64-gcc-libs")
    endif()
    if(packages)
      execute_process(COMMAND "${NOTICES_PACMAN}" -Qi ${packages} OUTPUT_VARIABLE info ERROR_QUIET)
      string(REPLACE ";" "," info "${info}")
      string(REPLACE "\n" ";" info "${info}")
      set(pkg "")
      foreach(line IN LISTS info)
        if(line MATCHES "^Name +: (.+)$")
          set(pkg "${CMAKE_MATCH_1}")
        elseif(pkg AND line MATCHES "^(Version|Description|URL|Licenses) +: (.+)$")
          set("${CMAKE_MATCH_1}_${pkg}" "${CMAKE_MATCH_2}")
        endif()
      endforeach()
      execute_process(COMMAND "${NOTICES_PACMAN}" -Ql ${query} OUTPUT_VARIABLE listing ERROR_QUIET)
      string(REPLACE "\n" ";" listing "${listing}")
      foreach(line IN LISTS listing)
        if(line MATCHES "^([^ ]+) (/.*/share/licenses/.*[^/])$")
          list(APPEND "texts_${CMAKE_MATCH_1}" "${msys}${CMAKE_MATCH_2}")
        elseif(line MATCHES "^([^ ]+) (/.*/share/.*/(LICEN[CS]E|COPYING|NOTICE)[^/]*)$")
          set(pkg "${CMAKE_MATCH_1}")
          set(path "${CMAKE_MATCH_2}")
          if(NOT path MATCHES "\\.gz$")  # not man pages
            list(APPEND "other_${pkg}" "${msys}${path}")  # e.g. share/icu/<version>/LICENSE
          endif()
        endif()
      endforeach()
      if(NOT texts_mingw-w64-x86_64-gcc)
        set(texts_mingw-w64-x86_64-gcc ${texts_mingw-w64-x86_64-gcc-libs})
      endif()
      # Standard licence texts by SPDX id (Qt carries most of them), for packages that ship none of their own.
      foreach(pkg IN LISTS query)
        if(NOT texts_${pkg})
          set("texts_${pkg}" ${other_${pkg}})
        endif()
        foreach(path IN LISTS "texts_${pkg}")
          get_filename_component(id "${path}" NAME_WLE)
          if(NOT DEFINED "standard_${id}")
            set("standard_${id}" "${path}")
          endif()
        endforeach()
      endforeach()
      foreach(pkg IN LISTS packages)
        if(texts_${pkg})
          continue()
        endif()
        string(REPLACE "spdx:" "" ids "${Licenses_${pkg}}")
        string(REGEX REPLACE " +" ";" ids "${ids}")
        foreach(id IN LISTS ids)
          string(REPLACE "-or-later" "-only" only "${id}")
          if(DEFINED "standard_${id}")
            list(APPEND "standard_texts_${pkg}" "${standard_${id}}")
          elseif(DEFINED "standard_${only}")
            list(APPEND "standard_texts_${pkg}" "${standard_${only}}")
          endif()
        endforeach()
      endforeach()
    endif()
  else()
    foreach(f IN LISTS lookup)
      get_filename_component(n "${f}" NAME)
      list(APPEND loose "${n}")
    endforeach()
  endif()
  list(REMOVE_DUPLICATES loose)

  # The text.
  set(inline TRUE)
  set(where "their full texts follow the list")
  if(NOTICES_LICENSES_DIR)
    set(inline FALSE)
    set(where "their licence files are in licenses/<package>/ beside this file")
  endif()
  set(rule "--------------------------------------------------------------------------------------------------------\n")
  string(CONCAT text "OPAD ${NOTICES_VERSION}: third-party notices\n"
    "========================================================================================================\n\n"
    "OPAD itself is free software under the MIT licence (LICENSE). ${NOTICES_SCOPE} Each component keeps its own "
    "licence, named below with the package it came from; ${where}.\n\n"
    "The libraries come from MSYS2 packages. Each package page (https://packages.msys2.org/package/<name>) links the "
    "exact source and build recipe of that version; the upstream projects are at the home pages listed.\n\n")
  set(body "")
  set(seen "")
  set(index 0)
  macro(_opad_notice_texts label paths)
    foreach(path IN LISTS ${paths})
      if(NOT EXISTS "${path}")
        continue()
      endif()
      get_filename_component(n "${path}" NAME)
      if(inline)
        file(READ "${path}" content)
        string(REPLACE "\r" "" content "${content}")
        string(SHA256 hash "${content}")
        if(DEFINED "seen_${hash}")
          string(APPEND body "${rule}${label}: ${n}\n${rule}(the same text as ${seen_${hash}})\n\n")
        else()
          set("seen_${hash}" "${label}: ${n}")
          string(APPEND body "${rule}${label}: ${n}\n${rule}${content}\n\n")
        endif()
      else()
        file(COPY "${path}" DESTINATION "${NOTICES_LICENSES_DIR}/${label}")
      endif()
    endforeach()
  endmacro()
  string(APPEND text "Components\n----------\n")
  if(occt_files)
    list(GET occt 1 occt_version)
    list(GET occt 2 occt_url)
    list(GET occt 3 occt_src)
    list(SORT occt_files)
    list(JOIN occt_files " " names)
    string(APPEND text "* opencascade ${occt_version}: Open CASCADE Technology, built from source by OPAD's build "
      "(cmake/occt_static.cmake)\n  Licence: LGPL-2.1-or-later WITH OCCT-exception-1.0\n  Home:    https://dev.opencascade.org\n"
      "  Source:  ${occt_url}\n  Files:   ${names}\n\n")
    set(occt_texts "${occt_src}/LICENSE_LGPL_21.txt" "${occt_src}/OCCT_LGPL_EXCEPTION.txt")
    _opad_notice_texts(opencascade occt_texts)
  endif()
  foreach(pkg IN LISTS packages)
    string(REGEX REPLACE "^mingw-w64-(x86_64|ucrt-x86_64|clang-x86_64)-" "" short "${pkg}")
    string(REGEX REPLACE " \\(mingw-w64\\)$" "" description "${Description_${pkg}}")
    string(REGEX REPLACE "spdx:" "" licence "${Licenses_${pkg}}")
    string(REGEX REPLACE "  +" " " licence "${licence}")
    if(short STREQUAL "gcc")
      set(description "GCC runtime libraries linked into the programs (libstdc++, libgcc)")
      set(licence "GPL-3.0-or-later WITH GCC-exception-3.1")
    endif()
    list(REMOVE_DUPLICATES "files_${pkg}")
    list(SORT "files_${pkg}")
    list(JOIN "files_${pkg}" " " names)
    string(APPEND text "* ${short} ${Version_${pkg}}: ${description}\n  Licence: ${licence}\n  Home:    ${URL_${pkg}}\n"
      "  Source:  https://packages.msys2.org/package/${pkg}\n  Files:   ${names}\n")
    if(NOT texts_${pkg} AND standard_texts_${pkg})
      string(APPEND text "  (the package carries no licence file: the standard text of its licence is given)\n")
      set("texts_${pkg}" ${standard_texts_${pkg}})
    elseif(NOT texts_${pkg})
      string(APPEND text "  (the package carries no licence file: see its home page)\n")
    endif()
    string(APPEND text "\n")
    _opad_notice_texts("${short}" "texts_${pkg}")
  endforeach()
  if(loose)
    list(SORT loose)
    list(JOIN loose " " names)
    if(NOTICES_PACMAN)
      string(APPEND text "* Not from an MSYS2 package (system or own files): ${names}\n\n")
    else()
      string(APPEND text "* Libraries (package information needs MSYS2's pacman, not found here): ${names}\n\n")
    endif()
  endif()
  if(NOTICES_EXTRA AND EXISTS "${NOTICES_EXTRA}")
    file(READ "${NOTICES_EXTRA}" extra)
    string(REPLACE "\r" "" extra "${extra}")
    string(APPEND text "${extra}\n")
  endif()
  if(inline AND body)
    string(APPEND text "\nLicence texts\n=============\n\n${body}")
  endif()

  set(old "")
  if(EXISTS "${NOTICES_OUT}")
    file(READ "${NOTICES_OUT}" old)
  endif()
  if(NOT old STREQUAL text)
    file(WRITE "${NOTICES_OUT}" "${text}")
  endif()
  if(NOTICES_CPP)
    string(FIND "${text}" ")opad_notices\"" clash)
    if(NOT clash EQUAL -1)
      message(FATAL_ERROR "notices.cmake: a licence text contains the raw-string delimiter )opad_notices\"")
    endif()
    string(CONCAT cpp "// Generated by cmake/notices.cmake from the link lines of this build; do not edit.\nnamespace opad::detail {\n"
      "const char* compiled_notices() {\n  return R\"opad_notices(" "${text}" ")opad_notices\";\n}\n}  // namespace opad::detail\n")
    set(old "")
    if(EXISTS "${NOTICES_CPP}")
      file(READ "${NOTICES_CPP}" old)
    endif()
    if(NOT old STREQUAL cpp)
      file(WRITE "${NOTICES_CPP}" "${cpp}")
    endif()
  endif()
  list(LENGTH packages count)
  message(STATUS "Third-party notices: ${count} packages -> ${NOTICES_OUT}")
endfunction()

if(NOTICES_OUT)
  _opad_notices()
endif()
